# This file was generated by GoReleaser. DO NOT EDIT.
class AwsWhois < Formula
  desc "CLI to find which aws resource are using a specific IP"
  homepage "https://github.com/luizm/aws-whois"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/luizm/aws-whois/releases/download/v1.0.0/aws-whois_1.0.0_darwin_amd64.tar.gz"
    sha256 "2525eab1631f874c2f4fc4daef64555cd962c063aea6ade4aaa26b234b9f1fd4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/luizm/aws-whois/releases/download/v1.0.0/aws-whois_1.0.0_linux_amd64.tar.gz"
      sha256 "8caef18ccea126156af678b001e2dcb75e0b5727a74c6f003b86ea3ff6c49608"
    end
  end

  def install
    bin.install "aws-whois"
  end

  test do
    system "#{bin}/aws-whois -h"
  end
end
