# This file was generated by GoReleaser. DO NOT EDIT.
class AwsWhois < Formula
  desc "CLI to find which aws resource are using a specific IP"
  homepage "https://github.com/luizm/aws-whois"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/luizm/aws-whois/releases/download/v1.0.1/aws-whois_1.0.1_darwin_amd64.tar.gz"
    sha256 "13343af918aa4e9876bd7e8e028f94d6ee28e785e3365ed58a1815d502623c1b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/luizm/aws-whois/releases/download/v1.0.1/aws-whois_1.0.1_linux_amd64.tar.gz"
      sha256 "eafe8440382b67390dda665581d3d830bdc80b63bc31a15d7b02c96a1f699a69"
    end
  end

  def install
    bin.install "aws-whois"
  end

  test do
    system "#{bin}/aws-whois -h"
  end
end
