# This file was generated by GoReleaser. DO NOT EDIT.
class EksLogin < Formula
  desc "CLI to automate the EKS login process using STS credentials created by vault."
  homepage "https://github.com/luizm/eks-login"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/luizm/eks-login/releases/download/v1.0.0/eks-login_1.0.0_darwin_amd64.tar.gz"
    sha256 "9758b0d13928ab665cf94832c828e5ce5789b01263ab0a45a503158c8e026d59"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/luizm/eks-login/releases/download/v1.0.0/eks-login_1.0.0_linux_amd64.tar.gz"
      sha256 "62b4d4c116a1db573b5c9e65ee0c7aabe80186206c8cc4f0cccb03f8d906480f"
    end
  end

  def install
    bin.install "eks-login"
  end

  test do
    system "#{bin}/eks-login -v"
  end
end
