# This file was generated by GoReleaser. DO NOT EDIT.
class Luizm < Formula
  desc "CLI to automate the EKS login process using STS credentials created by vault."
  homepage "https://github.com/luizm/eks-login"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/luizm/eks-login/releases/download/v1.0.1/eks-login_1.0.1_darwin_amd64.tar.gz"
    sha256 "0f1f152b6625604afbef2bfd2f13d5cd4a4c750e3bad6ad0fae9ae1a1359f4d1"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/luizm/eks-login/releases/download/v1.0.1/eks-login_1.0.1_linux_amd64.tar.gz"
      sha256 "6083ebf9c590e9b7b30247c7bd87fb85cbf7d9a0060e049ec4fa361dfed0ec86"
    end
  end

  def install
    bin.install "eks-login"
  end

  test do
    system "#{bin}/eks-login -v"
  end
end
